apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-app.fullname" . }}-server
  labels:
    {{- include "helm-app.labels" . | nindent 4 }}
    component: server
spec:
  replicas: {{ .Values.server.replicaCount }}
  strategy:
    {{- toYaml .Values.server.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "helm-app.selectorLabels" . | nindent 6 }}
      component: server
  template:
    metadata:
      labels:
        {{- include "helm-app.selectorLabels" . | nindent 8 }}
        component: server
        revision: "{{ now | unixEpoch }}"
    spec:
      containers:
        - name: {{ .Chart.Name }}-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5