name: Build
on:
  workflow_call:
    inputs:
      ENV:
        required: true
        type: string
env:
  REPOSITORY: ghcr.io/jauntin/n8n-workflows-search-engine
jobs:
  Build:
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.PAT_USER }}
          password: ${{ secrets.PAT }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REPOSITORY }}:${{ inputs.ENV }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
